### ISSUE TITLE
Rewrite K4LCIOReader as Gaudi Framework components

### ISSUE THREAD

**Issue by vvolkl** [ihep-sft-group/K4LCIOReader#1]
K4FWCore already offers some I/O functionality that could be useful here. Unless you think a standalone program has some advantages, I'd propose to rewrite the Reader/Converter as an Algorithm. I'll prepare a PR.

**Comment by zoujh** [comment]
On Mar. 3 edm4hep meeting, I reported the plan to write a LCIOInput algorithm. Then someone advises to provide a standalone reader/converter, so that we can use it somewhere else without Gaudi. I'm also preparing an Algorithm as a wrapper of this standalone reader, which makes use of the K4FWCore functionalities.

**Comment by zoujh** [comment]
Moreover, podio is expected to support multiple storage backends, as described in its document:
https://github.com/AIDASoft/podio/blob/master/doc/advanced_topics.md
Now ROOT I/O is provided in podio. It would be better if more storage backends are supported.
K4LCIOReader is not a complete LCIO backend. But obviously it is more flexible if there is less dependencies.

**Comment by vvolkl** [comment]
Hi @zoujh, thanks for your explanations!  I think there was a misunderstanding. I was suggesting to  include the code that does the conversion in edm4hep, similar to a method like this one for HepMC: https://github.com/key4hep/EDM4hep/blob/master/test/hepmc/edm4hep_testhepmc.cc#L18  Sorry about that. 

I agree on your point about the backends, although for FCC the ROOT backend will be sufficient for the near future, I think. But it is still good to have the interface that allows for other backends.

**Comment by zoujh** [comment]
Hi @vvolkl , that's fine. Thanks for your suggestion!
